import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";

const Home: NextPage = () => {
  const listenings = api.listening.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center">
        <div className="container flex flex-wrap items-center justify-center gap-4">
          {listenings.data
            ? listenings.data.map((listening, idx) => (
                <Link
                  key={idx}
                  scroll={false}
                  href={`/${listening.class}/${listening.url}/`}
                >
                  <div className="hover:bg-mumtaz-purple-light hover:border-mumtaz-purple m-4 block w-4/5 max-w-sm cursor-pointer rounded-lg border border-gray-200 bg-white p-6 text-center shadow-md transition-colors hover:bg-opacity-10 hover:shadow-lg md:min-w-[250px]">
                    {listening.title !== " " && (
                      <h5 className="font-fantasy mb-4 whitespace-nowrap text-2xl leading-loose text-gray-900">
                        {listening.title}
                      </h5>
                    )}

                    <p className="font-normal text-gray-700">
                      {listening.description}
                    </p>
                    <p className="font-normal capitalize text-gray-700">
                      {listening.type === "paper" || listening.type === "answer"
                        ? ""
                        : listening.type}
                    </p>
                    {!listening.description && (
                      <h5 className="font-fantasy text-2xl leading-loose tracking-tight text-gray-900">
                        {listening.title}
                      </h5>
                    )}
                  </div>
                </Link>
              ))
            : "Loading tRPC query..."}
        </div>
      </main>
    </>
  );
};

export default Home;
